import { API_ROUTES } from "@/app/constants/apiRoutes";

export const serviciosByNegocioRoute = (idNegocio: number) => API_ROUTES.serviciosByNegocio(idNegocio);
export const servicioByIdRoute = (idServicio: number) => API_ROUTES.servicioById(idServicio);
export const recursosByNegocioRoute = (idNegocio: number) => API_ROUTES.recursosByNegocio(idNegocio);
export const createServicioRoute = API_ROUTES.servicios;
export const updateServicioByIdRoute = (idServicio: number) => API_ROUTES.updateServicioById(idServicio);
export const deleteServicioByIdRoute = (idServicio: number) => API_ROUTES.deleteServicioById(idServicio);

export const SCREEN_TITLE = "Servicios";
export const ADD_SERVICE_BUTTON = "Añadir servicio";
export const SAVE_BUTTON_TEXT = "Guardar";
export const SAVE_CHANGES_BUTTON_TEXT = "Guardar cambios";
export const SAVING_BUTTON_TEXT = "Guardando...";
export const SAVING_CHANGES_BUTTON_TEXT = "Guardando cambios...";
export const EDIT_BUTTON_TEXT = "Editar";
export const DELETE_BUTTON_TEXT = "Eliminar";
export const DELETING_BUTTON_TEXT = "Eliminando...";
export const CONFIRM_DELETE_TITLE = "Eliminar servicio";
export const CONFIRM_DELETE_MESSAGE = "¿Seguro que quieres eliminar este servicio?";
export const CONFIRM_DELETE_CANCEL = "Cancelar";
export const CONFIRM_DELETE_ACCEPT = "Eliminar";
export const EMPTY_NOMBRE_ERROR = "El nombre del servicio es obligatorio";
export const EMPTY_PRECIO_ERROR = "El precio del servicio es obligatorio";
export const INVALID_PRECIO_ERROR = "El precio del servicio debe ser mayor que 0";
export const EMPTY_DURACION_ERROR = "La duración del servicio es obligatoria";
export const INVALID_DURACION_ERROR = "La duración del servicio debe ser un número entero mayor que 0";
export const EMPTY_DESCRIPCION_ERROR = "La descripción del servicio es obligatoria";
export const DEFAULT_FETCH_ERROR = "No se pudieron obtener los servicios";
export const DEFAULT_CREATE_ERROR = "No se pudo crear el servicio";
export const DEFAULT_UPDATE_ERROR = "No se pudieron guardar los cambios";
export const DEFAULT_DELETE_ERROR = "No se pudo eliminar el servicio";
export const CONNECTION_ERROR = "Error de conexión. Inténtalo de nuevo.";
export const SUCCESS_MESSAGE = "Servicio creado correctamente";
export const UPDATE_SUCCESS_MESSAGE = "Servicio actualizado correctamente";
export const DELETE_SUCCESS_MESSAGE = "Servicio eliminado correctamente";
export const EMPTY_SERVICIOS_MESSAGE = "No hay servicios registrados";
export const FORM_TITLE = "Nuevo servicio";
export const EDIT_FORM_TITLE = "Editar servicio";
export const DETAIL_SERVICE_TITLE = "Detalles del servicio";
export const DETAIL_NAME_LABEL = "Nombre";
export const DETAIL_PRICE_LABEL = "Precio";
export const DETAIL_DURATION_LABEL = "Duración";
export const DETAIL_DESCRIPTION_LABEL = "Descripción";
export const DETAIL_REQUIERE_CAPACIDAD_LABEL = "Requiere capacidad";
export const DETAIL_REQUIERE_CAPACIDAD_TRUE = "Sí";
export const DETAIL_REQUIERE_CAPACIDAD_FALSE = "No";
export const DETAIL_RECURSO_FAVORITO_LABEL = "Recurso favorito";
export const DETAIL_RECURSO_FAVORITO_NONE = "Sin recurso favorito";
export const NO_ACCESS_MESSAGE = "Solo jefe y administrador pueden gestionar servicios";
export const PRECIO_LABEL = "Precio";
export const DURACION_LABEL = "Duración";
export const DESCRIPCION_PLACEHOLDER = "Descripción";
export const REQUIERE_CAPACIDAD_LABEL = "Este servicio requiere capacidad";
export const RECURSO_FAVORITO_LABEL = "Recurso favorito (opcional)";
export const RECURSO_FAVORITO_SELECT_PLACEHOLDER = "Seleccionar recurso favorito";
export const RECURSO_FAVORITO_NONE_OPTION = "Sin recurso favorito";
export const RECURSO_FAVORITO_MODAL_TITLE = "Selecciona un recurso";
export const RECURSO_FAVORITO_LOADING = "Cargando recursos...";
export const RECURSO_FAVORITO_EMPTY = "No hay recursos disponibles";
export const JEFE_ROLE = "jefe";
export const ADMIN_ROLE = "admin";