import { API_ROUTES } from "@/app/constants/apiRoutes";

export const recursosByNegocioRoute = (idNegocio: number) => API_ROUTES.recursosByNegocio(idNegocio);
export const recursoByIdRoute = (idRecurso: number) => API_ROUTES.recursoById(idRecurso);
export const createRecursoRoute = API_ROUTES.recursos;
export const updateRecursoByIdRoute = (idRecurso: number) => API_ROUTES.updateRecursoById(idRecurso);
export const deleteRecursoByIdRoute = (idRecurso: number) => API_ROUTES.deleteRecursoById(idRecurso);

export const SCREEN_TITLE = "Recursos";
export const ADD_RESOURCE_BUTTON = "Añadir recurso";
export const SAVE_BUTTON_TEXT = "Guardar";
export const SAVE_CHANGES_BUTTON_TEXT = "Guardar cambios";
export const SAVING_BUTTON_TEXT = "Guardando...";
export const SAVING_CHANGES_BUTTON_TEXT = "Guardando cambios...";
export const EDIT_BUTTON_TEXT = "Editar";
export const DELETING_BUTTON_TEXT = "Eliminando...";
export const CONFIRM_DELETE_TITLE = "Eliminar recurso";
export const CONFIRM_DELETE_MESSAGE = "¿Seguro que quieres eliminar este recurso?";
export const CONFIRM_DELETE_CANCEL = "Cancelar";
export const CONFIRM_DELETE_ACCEPT = "Eliminar";
export const EMPTY_NOMBRE_ERROR = "El nombre del recurso es obligatorio";
export const EMPTY_CAPACIDAD_ERROR = "La capacidad del recurso es obligatoria";
export const INVALID_CAPACIDAD_ERROR = "La capacidad del recurso debe ser un número entero mayor que 0";
export const DEFAULT_FETCH_ERROR = "No se pudieron obtener los recursos";
export const DEFAULT_CREATE_ERROR = "No se pudo crear el recurso";
export const DEFAULT_UPDATE_ERROR = "No se pudieron guardar los cambios";
export const DEFAULT_DELETE_ERROR = "No se pudo eliminar el recurso";
export const CONNECTION_ERROR = "Error de conexión. Inténtalo de nuevo.";
export const SUCCESS_MESSAGE = "Recurso creado correctamente";
export const UPDATE_SUCCESS_MESSAGE = "Recurso actualizado correctamente";
export const DELETE_SUCCESS_MESSAGE = "Recurso eliminado correctamente";
export const EMPTY_RECURSOS_MESSAGE = "No hay recursos registrados";
export const FORM_TITLE = "Nuevo recurso";
export const EDIT_FORM_TITLE = "Editar recurso";
export const DETAIL_RESOURCE_TITLE = "Detalles del recurso";
export const DETAIL_NAME_LABEL = "Nombre";
export const DETAIL_CAPACITY_LABEL = "Capacidad";
export const NAME_PLACEHOLDER = "Nombre";
export const CAPACIDAD_PLACEHOLDER = "Capacidad";
export const RESERVA_INFO = "Asociable a una reserva";
export const JEFE_ROLE = "jefe";
export const ADMIN_ROLE = "admin";
